import { NextResponse } from "next/server";
import fs from "fs";
import { OPENCLAW_CONFIG_PATH } from "@/lib/openclaw-paths";

export async function GET() {
  try {
    let currentConfig = "{}";
    if (fs.existsSync(OPENCLAW_CONFIG_PATH)) {
      currentConfig = fs.readFileSync(OPENCLAW_CONFIG_PATH, "utf-8");
    }

    const scriptContent = `#!/bin/bash
# OpenClaw Auto Setup Script (Mac)
# Generated by OpenClaw Dashboard

echo "🦞 OpenClaw Mac Environment Setup"
echo "================================="

# 1. Check & Install OpenClaw
if ! command -v openclaw &> /dev/null; then
    echo "Installing OpenClaw CLI..."
    curl -fsSL https://openclaw.ai/install.sh | bash
else
    echo "✅ OpenClaw CLI already installed."
fi

# 2. Setup Configuration
CONFIG_DIR="$HOME/.openclaw"
CONFIG_FILE="$CONFIG_DIR/openclaw.json"

mkdir -p "$CONFIG_DIR"

echo "Writing configuration to $CONFIG_FILE..."
cat > "$CONFIG_FILE" << 'EOF'
${currentConfig}
EOF

echo "✅ Configuration updated."

# 3. Start Gateway
echo "Starting OpenClaw Gateway..."
# Ensure the path is correct after installation
export PATH=$PATH:$HOME/.openclaw/bin
openclaw gateway start &

echo "🎉 Setup Complete! You can close this window."
`;

    return new NextResponse(scriptContent, {
      headers: {
        "Content-Type": "application/x-sh",
        "Content-Disposition": 'attachment; filename="setup-openclaw.command"',
      },
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
